# Generated by Django 4.2.7 on 2023-11-25 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dose', models.TextField(max_length=10)),
                ('description', models.TextField(max_length=300)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_address', models.TextField(max_length=300)),
                ('Patient_bloodtype', models.CharField(choices=[('A', 'A'), ('AB', 'AB'), ('B', 'B'), ('O', 'O'), ('-', 'None')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('diagnose', models.TextField(max_length=300)),
                ('notes', models.TextField(max_length=300)),
                ('follow_up', models.DateTimeField()),
                ('patient_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientprofile')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.medcabinet')),
            ],
        ),
    ]
