# Generated by Django 4.2.7 on 2023-11-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientrecords',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='patientrecords',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
