# Generated by Django 4.2.7 on 2023-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_patientrecords_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecords',
            name='follow_up',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
