# Generated by Django 4.2.7 on 2023-11-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_patientrecords_follow_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecords',
            name='prescription',
        ),
        migrations.AddField(
            model_name='patientrecords',
            name='prescription',
            field=models.ManyToManyField(to='records.medcabinet'),
        ),
    ]
