# Generated by Django 4.2.7 on 2023-11-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_patientrecords_prescription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'ordering': ['patient_name']},
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_apply',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_comorbid',
            field=models.TextField(default='No Comorbid'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_diastol',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_note',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_systol',
            field=models.IntegerField(default=120),
        ),
    ]
